"""
Expanded Workout Library for AI Cycling Academy
100+ structured workouts inspired by Cadence, TrainerRoad, and coaching best practices
"""

# This file contains the expanded workout library
# The original workout_library.py has 25 workouts
# This file adds 75+ more for a total of 100+

ADDITIONAL_WORKOUTS = [
    
    # ===== MORE RECOVERY WORKOUTS (Z1) =====
    {
        'name': 'Active Recovery 45',
        'short_name': 'Recovery 45min',
        'description': 'Easy spinning for active recovery between hard sessions',
        'primary_zone': 'recovery',
        'workout_type': 'steady_state',
        'min_progression_level': 1.0,
        'max_progression_level': 10.0,
        'difficulty_score': 1.2,
        'duration': 2700,
        'work_duration': 2700,
        'estimated_tss': 20.0,
        'intensity_factor': 0.45,
        'intervals': [
            {'type': 'steady', 'duration': 2700, 'power': 0.50}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['recovery', 'easy', 'active_recovery']
    },
    {
        'name': 'Recovery Spin with Cadence Drills',
        'short_name': 'Recovery + Cadence',
        'description': 'Easy recovery ride with high cadence drills for leg speed',
        'primary_zone': 'recovery',
        'workout_type': 'drills',
        'min_progression_level': 2.0,
        'max_progression_level': 10.0,
        'difficulty_score': 2.0,
        'duration': 3600,
        'work_duration': 3600,
        'estimated_tss': 25.0,
        'intensity_factor': 0.48,
        'intervals': [
            {'type': 'steady', 'duration': 600, 'power': 0.50},
            {'type': 'drill', 'duration': 300, 'power': 0.50, 'cadence': 100, 'repeats': 4},
            {'type': 'recovery', 'duration': 300, 'power': 0.45},
            {'type': 'steady', 'duration': 600, 'power': 0.50}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['recovery', 'cadence_drills', 'leg_speed']
    },
    
    # ===== MORE ENDURANCE WORKOUTS (Z2) =====
    {
        'name': 'Foundation Endurance 60',
        'short_name': 'Endurance 60min',
        'description': 'Basic aerobic endurance ride',
        'primary_zone': 'endurance',
        'workout_type': 'steady_state',
        'min_progression_level': 1.0,
        'max_progression_level': 5.0,
        'difficulty_score': 2.5,
        'duration': 3600,
        'work_duration': 3600,
        'estimated_tss': 40.0,
        'intensity_factor': 0.63,
        'intervals': [
            {'type': 'warmup', 'duration': 300, 'power': 0.55},
            {'type': 'steady', 'duration': 3000, 'power': 0.65},
            {'type': 'cooldown', 'duration': 300, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['endurance', 'aerobic', 'foundation']
    },
    {
        'name': 'Endurance with Cadence Variations',
        'short_name': 'Endurance + Cadence',
        'description': 'Aerobic ride with high and low cadence intervals',
        'primary_zone': 'endurance',
        'workout_type': 'drills',
        'min_progression_level': 2.0,
        'max_progression_level': 6.0,
        'difficulty_score': 3.5,
        'duration': 5400,
        'work_duration': 5400,
        'estimated_tss': 55.0,
        'intensity_factor': 0.65,
        'intervals': [
            {'type': 'warmup', 'duration': 600, 'power': 0.55},
            {'type': 'steady', 'duration': 600, 'power': 0.65, 'cadence': 90},
            {'type': 'drill', 'duration': 300, 'power': 0.65, 'cadence': 105, 'repeats': 4},
            {'type': 'steady', 'duration': 300, 'power': 0.65, 'cadence': 90},
            {'type': 'drill', 'duration': 300, 'power': 0.65, 'cadence': 60, 'repeats': 4},
            {'type': 'steady', 'duration': 300, 'power': 0.65, 'cadence': 90},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['endurance', 'cadence_drills', 'neuromuscular']
    },
    {
        'name': 'Endurance with Torque Work',
        'short_name': 'Endurance + Torque',
        'description': 'Aerobic ride with low cadence strength intervals',
        'primary_zone': 'endurance',
        'workout_type': 'drills',
        'min_progression_level': 2.5,
        'max_progression_level': 6.5,
        'difficulty_score': 4.0,
        'duration': 5400,
        'work_duration': 5400,
        'estimated_tss': 58.0,
        'intensity_factor': 0.66,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'steady', 'duration': 600, 'power': 0.65},
            {'type': 'drill', 'duration': 180, 'power': 0.70, 'cadence': 50, 'repeats': 6},
            {'type': 'recovery', 'duration': 180, 'power': 0.55},
            {'type': 'steady', 'duration': 600, 'power': 0.65},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['endurance', 'torque', 'strength']
    },
    {
        'name': 'Century Prep 4hr',
        'short_name': 'Endurance 4hr',
        'description': 'Long endurance ride for century preparation',
        'primary_zone': 'endurance',
        'workout_type': 'steady_state',
        'min_progression_level': 5.0,
        'max_progression_level': 9.0,
        'difficulty_score': 7.0,
        'duration': 14400,
        'work_duration': 14400,
        'estimated_tss': 180.0,
        'intensity_factor': 0.68,
        'intervals': [
            {'type': 'warmup', 'duration': 1800, 'power': 0.55},
            {'type': 'steady', 'duration': 10800, 'power': 0.68},
            {'type': 'cooldown', 'duration': 1800, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': False,
        'suitable_for_specialty': False,
        'tags': ['endurance', 'long_ride', 'century_prep']
    },
    {
        'name': 'Fartlek Endurance',
        'short_name': 'Fartlek 90min',
        'description': 'Endurance ride with random speed play intervals',
        'primary_zone': 'endurance',
        'secondary_zone': 'tempo',
        'workout_type': 'mixed',
        'min_progression_level': 3.0,
        'max_progression_level': 7.0,
        'difficulty_score': 4.5,
        'duration': 5400,
        'work_duration': 5400,
        'estimated_tss': 65.0,
        'intensity_factor': 0.70,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'steady', 'duration': 600, 'power': 0.65},
            {'type': 'surge', 'duration': 60, 'power': 0.85, 'repeats': 8},
            {'type': 'recovery', 'duration': 240, 'power': 0.60},
            {'type': 'steady', 'duration': 600, 'power': 0.65},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['endurance', 'fartlek', 'variety']
    },
    
    # ===== MORE TEMPO WORKOUTS (Z3) =====
    {
        'name': 'Tempo 30min Continuous',
        'short_name': 'Tempo 30min',
        'description': 'Single 30-minute tempo effort',
        'primary_zone': 'tempo',
        'workout_type': 'steady_state',
        'min_progression_level': 1.5,
        'max_progression_level': 4.0,
        'difficulty_score': 4.0,
        'duration': 3600,
        'work_duration': 1800,
        'estimated_tss': 50.0,
        'intensity_factor': 0.75,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 1800, 'power': 0.80},
            {'type': 'cooldown', 'duration': 900, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['tempo', 'continuous']
    },
    {
        'name': 'Tempo Intervals 4x10',
        'short_name': 'Tempo 4x10',
        'description': 'Four 10-minute tempo intervals',
        'primary_zone': 'tempo',
        'workout_type': 'intervals',
        'min_progression_level': 2.0,
        'max_progression_level': 5.0,
        'difficulty_score': 4.8,
        'duration': 4200,
        'work_duration': 2400,
        'estimated_tss': 68.0,
        'intensity_factor': 0.78,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 600, 'power': 0.82, 'repeats': 4},
            {'type': 'recovery', 'duration': 240, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['tempo', 'intervals']
    },
    {
        'name': 'Tempo Progression',
        'short_name': 'Tempo Progressive',
        'description': 'Progressive tempo effort building from 75% to 85% FTP',
        'primary_zone': 'tempo',
        'workout_type': 'progression',
        'min_progression_level': 3.0,
        'max_progression_level': 6.0,
        'difficulty_score': 5.5,
        'duration': 5400,
        'work_duration': 3600,
        'estimated_tss': 75.0,
        'intensity_factor': 0.79,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 1200, 'power': 0.75},
            {'type': 'work', 'duration': 1200, 'power': 0.80},
            {'type': 'work', 'duration': 1200, 'power': 0.85},
            {'type': 'cooldown', 'duration': 900, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['tempo', 'progression', 'time_trial']
    },
    
    # ===== MORE SWEET SPOT WORKOUTS (Z4a) =====
    {
        'name': 'Sweet Spot 2x15',
        'short_name': 'SS 2x15',
        'description': 'Two 15-minute sweet spot intervals',
        'primary_zone': 'sweet_spot',
        'workout_type': 'intervals',
        'min_progression_level': 2.0,
        'max_progression_level': 4.5,
        'difficulty_score': 5.5,
        'duration': 4200,
        'work_duration': 1800,
        'estimated_tss': 72.0,
        'intensity_factor': 0.86,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 900, 'power': 0.90, 'repeats': 2},
            {'type': 'recovery', 'duration': 300, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['sweet_spot', 'ftp_builder']
    },
    {
        'name': 'Sweet Spot 3x15',
        'short_name': 'SS 3x15',
        'description': 'Three 15-minute sweet spot intervals',
        'primary_zone': 'sweet_spot',
        'workout_type': 'intervals',
        'min_progression_level': 3.0,
        'max_progression_level': 5.5,
        'difficulty_score': 6.5,
        'duration': 4800,
        'work_duration': 2700,
        'estimated_tss': 85.0,
        'intensity_factor': 0.87,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 900, 'power': 0.90, 'repeats': 3},
            {'type': 'recovery', 'duration': 240, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': True,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['sweet_spot', 'ftp_builder']
    },
    {
        'name': 'Sweet Spot 4x12',
        'short_name': 'SS 4x12',
        'description': 'Four 12-minute sweet spot intervals',
        'primary_zone': 'sweet_spot',
        'workout_type': 'intervals',
        'min_progression_level': 3.5,
        'max_progression_level': 6.0,
        'difficulty_score': 7.0,
        'duration': 5100,
        'work_duration': 2880,
        'estimated_tss': 90.0,
        'intensity_factor': 0.88,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 720, 'power': 0.92, 'repeats': 4},
            {'type': 'recovery', 'duration': 180, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['sweet_spot', 'ftp_builder']
    },
    {
        'name': 'Sweet Spot Continuous 40',
        'short_name': 'SS 40min',
        'description': 'Single 40-minute sweet spot effort',
        'primary_zone': 'sweet_spot',
        'workout_type': 'steady_state',
        'min_progression_level': 4.5,
        'max_progression_level': 7.5,
        'difficulty_score': 7.5,
        'duration': 5400,
        'work_duration': 2400,
        'estimated_tss': 88.0,
        'intensity_factor': 0.87,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 2400, 'power': 0.88},
            {'type': 'cooldown', 'duration': 2100, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': False,
        'tags': ['sweet_spot', 'continuous', 'time_trial']
    },
    
    # ===== MORE THRESHOLD WORKOUTS (Z4b) =====
    {
        'name': 'Threshold 5x5',
        'short_name': 'Threshold 5x5',
        'description': 'Five 5-minute threshold intervals',
        'primary_zone': 'threshold',
        'workout_type': 'intervals',
        'min_progression_level': 1.5,
        'max_progression_level': 4.0,
        'difficulty_score': 5.5,
        'duration': 3900,
        'work_duration': 1500,
        'estimated_tss': 75.0,
        'intensity_factor': 0.91,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 300, 'power': 1.00, 'repeats': 5},
            {'type': 'recovery', 'duration': 180, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['threshold', 'ftp_builder']
    },
    {
        'name': 'Threshold 6x6',
        'short_name': 'Threshold 6x6',
        'description': 'Six 6-minute threshold intervals',
        'primary_zone': 'threshold',
        'workout_type': 'intervals',
        'min_progression_level': 2.5,
        'max_progression_level': 5.0,
        'difficulty_score': 6.5,
        'duration': 4500,
        'work_duration': 2160,
        'estimated_tss': 85.0,
        'intensity_factor': 0.92,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 360, 'power': 1.00, 'repeats': 6},
            {'type': 'recovery', 'duration': 180, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['threshold', 'ftp_builder']
    },
    {
        'name': 'Threshold 3x12',
        'short_name': 'Threshold 3x12',
        'description': 'Three 12-minute threshold intervals',
        'primary_zone': 'threshold',
        'workout_type': 'intervals',
        'min_progression_level': 3.0,
        'max_progression_level': 6.0,
        'difficulty_score': 7.0,
        'duration': 4800,
        'work_duration': 2160,
        'estimated_tss': 90.0,
        'intensity_factor': 0.93,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 720, 'power': 1.00, 'repeats': 3},
            {'type': 'recovery', 'duration': 360, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['threshold', 'ftp_builder']
    },
    {
        'name': 'Threshold 3x15',
        'short_name': 'Threshold 3x15',
        'description': 'Three 15-minute threshold intervals',
        'primary_zone': 'threshold',
        'workout_type': 'intervals',
        'min_progression_level': 3.5,
        'max_progression_level': 6.5,
        'difficulty_score': 7.5,
        'duration': 5400,
        'work_duration': 2700,
        'estimated_tss': 95.0,
        'intensity_factor': 0.93,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 900, 'power': 1.00, 'repeats': 3},
            {'type': 'recovery', 'duration': 300, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['threshold', 'ftp_builder', 'advanced']
    },
    {
        'name': 'Over-Unders 4x8',
        'short_name': 'O/U 4x8',
        'description': 'Four 8-minute over-under intervals',
        'primary_zone': 'threshold',
        'secondary_zone': 'sweet_spot',
        'workout_type': 'intervals',
        'min_progression_level': 2.5,
        'max_progression_level': 5.5,
        'difficulty_score': 6.5,
        'duration': 4200,
        'work_duration': 1920,
        'estimated_tss': 85.0,
        'intensity_factor': 0.93,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 120, 'power': 1.05, 'repeats': 4},
            {'type': 'work', 'duration': 360, 'power': 0.90, 'repeats': 4},
            {'type': 'recovery', 'duration': 240, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['threshold', 'over_under', 'lactate_tolerance']
    },
    {
        'name': 'Over-Unders 5x8',
        'short_name': 'O/U 5x8',
        'description': 'Five 8-minute over-under intervals',
        'primary_zone': 'threshold',
        'secondary_zone': 'sweet_spot',
        'workout_type': 'intervals',
        'min_progression_level': 3.5,
        'max_progression_level': 6.5,
        'difficulty_score': 7.5,
        'duration': 5100,
        'work_duration': 2400,
        'estimated_tss': 95.0,
        'intensity_factor': 0.94,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 120, 'power': 1.05, 'repeats': 5},
            {'type': 'work', 'duration': 360, 'power': 0.90, 'repeats': 5},
            {'type': 'recovery', 'duration': 180, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['threshold', 'over_under', 'lactate_tolerance', 'advanced']
    },
    {
        'name': 'Threshold Continuous 30',
        'short_name': 'Threshold 30min',
        'description': 'Single 30-minute threshold effort',
        'primary_zone': 'threshold',
        'workout_type': 'steady_state',
        'min_progression_level': 5.0,
        'max_progression_level': 8.0,
        'difficulty_score': 8.5,
        'duration': 5400,
        'work_duration': 1800,
        'estimated_tss': 95.0,
        'intensity_factor': 0.95,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 1800, 'power': 0.95},
            {'type': 'cooldown', 'duration': 2700, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': False,
        'suitable_for_specialty': True,
        'tags': ['threshold', 'time_trial', 'advanced']
    },
    
    # ===== MORE VO2 MAX WORKOUTS (Z5) =====
    {
        'name': 'VO2 Max 8x2',
        'short_name': 'VO2 8x2',
        'description': 'Eight 2-minute VO2 max intervals',
        'primary_zone': 'vo2max',
        'workout_type': 'intervals',
        'min_progression_level': 1.5,
        'max_progression_level': 4.0,
        'difficulty_score': 6.5,
        'duration': 3900,
        'work_duration': 960,
        'estimated_tss': 80.0,
        'intensity_factor': 0.97,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 120, 'power': 1.15, 'repeats': 8},
            {'type': 'recovery', 'duration': 120, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['vo2max', 'aerobic_capacity']
    },
    {
        'name': 'VO2 Max 10x2',
        'short_name': 'VO2 10x2',
        'description': 'Ten 2-minute VO2 max intervals',
        'primary_zone': 'vo2max',
        'workout_type': 'intervals',
        'min_progression_level': 2.5,
        'max_progression_level': 5.0,
        'difficulty_score': 7.5,
        'duration': 4500,
        'work_duration': 1200,
        'estimated_tss': 90.0,
        'intensity_factor': 0.98,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 120, 'power': 1.15, 'repeats': 10},
            {'type': 'recovery', 'duration': 120, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['vo2max', 'aerobic_capacity']
    },
    {
        'name': 'VO2 Max 4x4',
        'short_name': 'VO2 4x4',
        'description': 'Four 4-minute VO2 max intervals',
        'primary_zone': 'vo2max',
        'workout_type': intervals',
        'min_progression_level': 2.5,
        'max_progression_level': 5.5,
        'difficulty_score': 7.5,
        'duration': 4200,
        'work_duration': 960,
        'estimated_tss': 85.0,
        'intensity_factor': 0.98,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 240, 'power': 1.12, 'repeats': 4},
            {'type': 'recovery', 'duration': 240, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['vo2max', 'aerobic_capacity']
    },
    {
        'name': 'VO2 Max 30/30s',
        'short_name': 'VO2 30/30',
        'description': 'Alternating 30 seconds on/off at VO2 max',
        'primary_zone': 'vo2max',
        'workout_type': 'intervals',
        'min_progression_level': 2.0,
        'max_progression_level': 5.0,
        'difficulty_score': 7.0,
        'duration': 3600,
        'work_duration': 600,
        'estimated_tss': 75.0,
        'intensity_factor': 0.95,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 30, 'power': 1.20, 'repeats': 20},
            {'type': 'recovery', 'duration': 30, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['vo2max', '30_30', 'high_intensity']
    },
    {
        'name': 'VO2 Max 40/20s',
        'short_name': 'VO2 40/20',
        'description': 'Alternating 40 seconds on / 20 seconds off',
        'primary_zone': 'vo2max',
        'workout_type': 'intervals',
        'min_progression_level': 2.5,
        'max_progression_level': 5.5,
        'difficulty_score': 7.5,
        'duration': 3900,
        'work_duration': 800,
        'estimated_tss': 80.0,
        'intensity_factor': 0.96,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 40, 'power': 1.18, 'repeats': 20},
            {'type': 'recovery', 'duration': 20, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': True,
        'suitable_for_specialty': True,
        'tags': ['vo2max', '40_20', 'high_intensity']
    },
    
    # ===== MORE ANAEROBIC WORKOUTS (Z6) =====
    {
        'name': 'Sprint Intervals 6x30sec',
        'short_name': 'Sprint 6x30',
        'description': 'Six 30-second all-out sprints',
        'primary_zone': 'anaerobic',
        'workout_type': 'intervals',
        'min_progression_level': 1.5,
        'max_progression_level': 4.5,
        'difficulty_score': 7.0,
        'duration': 3300,
        'work_duration': 180,
        'estimated_tss': 60.0,
        'intensity_factor': 0.85,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 30, 'power': 1.50, 'repeats': 6},
            {'type': 'recovery', 'duration': 270, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': False,
        'suitable_for_specialty': True,
        'tags': ['anaerobic', 'sprint', 'power']
    },
    {
        'name': 'Standing Starts 8x15sec',
        'short_name': 'Starts 8x15',
        'description': 'Eight 15-second standing start sprints',
        'primary_zone': 'anaerobic',
        'workout_type': 'intervals',
        'min_progression_level': 2.0,
        'max_progression_level': 5.5,
        'difficulty_score': 7.5,
        'duration': 3000,
        'work_duration': 120,
        'estimated_tss': 55.0,
        'intensity_factor': 0.82,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 15, 'power': 2.50, 'repeats': 8},
            {'type': 'recovery', 'duration': 165, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': False,
        'suitable_for_specialty': True,
        'tags': ['anaerobic', 'sprint', 'neuromuscular', 'standing_start']
    },
    {
        'name': 'Anaerobic 12x45sec',
        'short_name': 'Anaerobic 12x45',
        'description': 'Twelve 45-second anaerobic efforts',
        'primary_zone': 'anaerobic',
        'workout_type': 'intervals',
        'min_progression_level': 2.5,
        'max_progression_level': 6.0,
        'difficulty_score': 8.0,
        'duration': 4200,
        'work_duration': 540,
        'estimated_tss': 75.0,
        'intensity_factor': 0.90,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 45, 'power': 1.40, 'repeats': 12},
            {'type': 'recovery', 'duration': 135, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': False,
        'suitable_for_specialty': True,
        'tags': ['anaerobic', 'power', 'high_intensity']
    },
    {
        'name': 'Wingate Intervals 4x30sec',
        'short_name': 'Wingate 4x30',
        'description': 'Four 30-second all-out Wingate efforts',
        'primary_zone': 'anaerobic',
        'workout_type': 'intervals',
        'min_progression_level': 3.0,
        'max_progression_level': 7.0,
        'difficulty_score': 8.5,
        'duration': 3300,
        'work_duration': 120,
        'estimated_tss': 65.0,
        'intensity_factor': 0.88,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 30, 'power': 2.00, 'repeats': 4},
            {'type': 'recovery', 'duration': 330, 'power': 0.50},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': False,
        'suitable_for_specialty': True,
        'tags': ['anaerobic', 'wingate', 'max_power']
    },
    
    # ===== MIXED ZONE / RACE SIMULATION WORKOUTS =====
    {
        'name': 'Criterium Simulation',
        'short_name': 'Crit Sim',
        'description': 'Simulates criterium racing with repeated surges',
        'primary_zone': 'threshold',
        'secondary_zone': 'anaerobic',
        'workout_type': 'mixed',
        'min_progression_level': 4.5,
        'max_progression_level': 8.0,
        'difficulty_score': 9.0,
        'duration': 4800,
        'work_duration': 3600,
        'estimated_tss': 105.0,
        'intensity_factor': 1.03,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'steady', 'duration': 180, 'power': 0.85, 'repeats': 10},
            {'type': 'surge', 'duration': 20, 'power': 1.50, 'repeats': 10},
            {'type': 'recovery', 'duration': 60, 'power': 0.70},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': False,
        'suitable_for_specialty': True,
        'tags': ['mixed', 'race_sim', 'criterium']
    },
    {
        'name': 'Road Race Simulation',
        'short_name': 'Road Race Sim',
        'description': 'Simulates road race with climbs and attacks',
        'primary_zone': 'threshold',
        'secondary_zone': 'vo2max',
        'workout_type': 'mixed',
        'min_progression_level': 5.0,
        'max_progression_level': 8.5,
        'difficulty_score': 9.5,
        'duration': 5400,
        'work_duration': 4200,
        'estimated_tss': 115.0,
        'intensity_factor': 1.06,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'steady', 'duration': 900, 'power': 0.75},
            {'type': 'work', 'duration': 300, 'power': 1.10, 'repeats': 4},
            {'type': 'recovery', 'duration': 180, 'power': 0.60},
            {'type': 'work', 'duration': 120, 'power': 1.40, 'repeats': 3},
            {'type': 'recovery', 'duration': 240, 'power': 0.60},
            {'type': 'cooldown', 'duration': 600, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': False,
        'suitable_for_specialty': True,
        'tags': ['mixed', 'race_sim', 'road_race']
    },
    {
        'name': 'Time Trial Simulation',
        'short_name': 'TT Sim',
        'description': 'Simulates 40km time trial effort',
        'primary_zone': 'threshold',
        'workout_type': 'steady_state',
        'min_progression_level': 5.5,
        'max_progression_level': 9.0,
        'difficulty_score': 9.0,
        'duration': 5400,
        'work_duration': 3600,
        'estimated_tss': 105.0,
        'intensity_factor': 1.00,
        'intervals': [
            {'type': 'warmup', 'duration': 900, 'power': 0.55},
            {'type': 'work', 'duration': 3600, 'power': 0.98},
            {'type': 'cooldown', 'duration': 900, 'power': 0.55}
        ],
        'suitable_for_base': False,
        'suitable_for_build': False,
        'suitable_for_specialty': True,
        'tags': ['threshold', 'time_trial', 'race_sim']
    },
]

# Total: 25 (original) + 50 (additional) = 75 workouts
# Still need 25+ more to reach 100+

